name: Run Cypress Tests

# Run this workflow on every push or pull request to the main branch
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repository code
      - name: Check out code
        uses: actions/checkout@v3

      # 2) Set up Node.js (adjust version if needed)
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3) Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4) Run Cypress tests in headless mode
      - name: Run Cypress Tests
        run: npx cypress run
